package com.padcmyanmar.suhlaing.movieappbookingassignment.dummy

import com.padcmyanmar.suhlaing.movieappbookingassignment.data.vos.*

val DUMMY_SEATS = listOf(
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_EMPTY),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_EMPTY),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_TAKEN),
    MovieSeatVo(title = "", type = SEAT_TYPE_TAKEN),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_TAKEN),
    MovieSeatVo(title = "", type = SEAT_TYPE_TAKEN),
    MovieSeatVo(title = "", type = SEAT_TYPE_TAKEN),
    MovieSeatVo(title = "A",type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "", type = SEAT_TYPE_AVAILAVE),
    MovieSeatVo(title = "A",type = SEAT_TYPE_TEXT),
)